export App from './App/App';
export NotFound from './NotFound/NotFound';
export Auth from './Auth/Auth';
export Step from './Auth/Step/Step';
export Form1 from './Auth/Forms/Form1/Form';
export Form2 from './Auth/Forms/Form2/Form';
export Form3 from './Auth/Forms/Form3/Form';
export Form4 from './Auth/Forms/Form4/Form';
export Profile from './Auth/Forms/Profile/Profile';
